# Generated by Django 5.1.6 on 2025-02-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='Slug',
            field=models.SlugField(blank=True, max_length=1000, null=True),
        ),
    ]
