# Generated by Django 5.1.6 on 2025-02-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_blogmodel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='Slug',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=1000, null=True),
        ),
    ]
